pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Start Building Dockerfile........'
                docker build -f mynodeapp/Dockerfile -t lakshithah1/mynodeapp mynodeapp
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
