pipeline {

    options
    {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    agent any



    environment 
    {
        IMAGE = 'mynodeapp:latest'
        VERSION = 'latest'
        PROJECT = 'mynodeapp'
        ECRLOCATION = '936825406282.dkr.ecr.ap-southeast-1.amazonaws.com'
    }
    stages {

        stage('Build preparations'){
            steps{
                script {
                    // calculate GIT lastest commit short-hash
                    gitCommitHash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    shortCommitHash = gitCommitHash.take(7)
                    // calculate a sample version tag
                    VERSION = shortCommitHash
                    IMAGE = "#$PROJECT:$VERSION"
                    // set the build display name
                    currentBuild.displayName = "#${BUILD_ID}-${VERSION}"
                    sh 'echo ${IMAGE}'
                    sh 'echo ${VERSION}'
                }
            }
        }

        stage('Build') {
            steps {
                    sh 'echo ${shortCommitHash}'
                    sh 'echo ${BUILD_ID}'
                    sh 'docker build -f ECS/mynodeapp/Dockerfile -t $IMAGE ECS/mynodeapp'
            }
        }
        stage('Tag') {
            steps {
                script
                {
                    sh 'docker tag ${IMAGE} ${ECRLOCATION}/${IMAGE}'
                }
            }
        }
        stage('Deploy') {
            steps {
            script
                {
                    echo 'Push Image to Registry.......'
                    sh("eval \$(aws ecr get-login --no-include-email --region ap-southeast-1 | sed 's|https://||')")
                    sh 'docker push ${ECRLOCATION}/${IMAGE}'
                }
            }
        }
    }
}
