pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Start Building Dockerfile........'
                sh 'docker build -f ECS/mynodeapp/Dockerfile -t mynodeapp ECS/mynodeapp'
            }
        }
        stage('Tag') {
            steps {
                echo 'Tag Image........'
                sh 'docker tag mynodeapp:latest 936825406282.dkr.ecr.ap-southeast-1.amazonaws.com/mynodeapp:latest'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Push Image to Registry.......'
                sh("eval \$(aws ecr get-login --no-include-email --region ap-southeast-1 | sed 's|https://||')")
                sh 'docker push 936825406282.dkr.ecr.ap-southeast-1.amazonaws.com/mynodeapp:latest'
            }
        }
    }
}
